"""
Self-audit: compare Week 1 hand-written doc (ARCHITECTURE_NOTES.md or RECONNAISSANCE.md)
with auto-generated CODEBASE.md and write a discrepancy report.
"""

import re
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

WEEK1_DOC_NAMES = ["ARCHITECTURE_NOTES.md", "RECONNAISSANCE.md", "ARCHITECTURE.md"]


def _find_week1_doc(repo_path: Path) -> Optional[Path]:
    """Return path to first found Week 1 doc in repo root."""
    for name in WEEK1_DOC_NAMES:
        p = repo_path / name
        if p.exists() and p.is_file():
            return p
    return None


def _section_headings(content: str) -> set[str]:
    """Extract markdown ## headings (normalized to lowercase)."""
    return {m.strip().lower() for m in re.findall(r"^##\s+(.+)$", content, re.MULTILINE)}


def _key_phrases(content: str, limit: int = 50) -> set[str]:
    """Extract likely key phrases (lines that look like list items or module paths)."""
    phrases = set()
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("-") or line.startswith("*"):
            line = line.lstrip("-* ").strip()
        if "`" in line:
            for m in re.finditer(r"`([^`]+)`", line):
                phrases.add(m.group(1).lower())
        if len(line) > 3 and len(line) < 120:
            phrases.add(line.lower()[:80])
    return set(list(phrases)[:limit])


def run_self_audit(
    week1_repo_path: Path,
    output_dir: Optional[Path] = None,
) -> Path:
    """
    Compare Week 1 doc with CODEBASE.md and write .cartography/self_audit_report.md.
    week1_repo_path: path to Week 1 repo (should contain ARCHITECTURE_NOTES.md or RECONNAISSANCE.md).
    output_dir: where .cartography lives (default: week1_repo_path/.cartography).
    Returns path to written report.
    """
    repo_path = Path(week1_repo_path).resolve()
    out = Path(output_dir) if output_dir else repo_path / ".cartography"
    out.mkdir(parents=True, exist_ok=True)

    codebase_md = out / "CODEBASE.md"
    if not codebase_md.exists():
        raise FileNotFoundError(
            f"CODEBASE.md not found at {codebase_md}. Run 'cartographer full {repo_path}' first."
        )

    week1_doc = _find_week1_doc(repo_path)
    if not week1_doc:
        raise FileNotFoundError(
            f"No Week 1 doc found in {repo_path} (looked for {WEEK1_DOC_NAMES})."
        )

    codebase_text = codebase_md.read_text(encoding="utf-8", errors="replace")
    week1_text = week1_doc.read_text(encoding="utf-8", errors="replace")

    codebase_sections = _section_headings(codebase_text)
    week1_sections = _section_headings(week1_text)
    codebase_phrases = _key_phrases(codebase_text)
    week1_phrases = _key_phrases(week1_text)

    discrepancies = []

    only_in_codebase = codebase_sections - week1_sections
    if only_in_codebase:
        discrepancies.append({
            "type": "Sections only in CODEBASE.md",
            "detail": ", ".join(sorted(only_in_codebase)),
            "explanation": "Static analysis and Archivist produce structured sections (e.g. Critical Path, Data Sources) that may not appear in hand-written notes.",
        })

    only_in_week1 = week1_sections - codebase_sections
    if only_in_week1:
        discrepancies.append({
            "type": "Sections only in Week 1 doc",
            "detail": ", ".join(sorted(only_in_week1)),
            "explanation": "Hand-written doc may include narrative or sections (e.g. manual findings) not generated by the pipeline.",
        })

    overlap_phrases = codebase_phrases & week1_phrases
    only_codebase_phrases = codebase_phrases - week1_phrases
    if len(only_codebase_phrases) > 5:
        sample = list(only_codebase_phrases)[:5]
        discrepancies.append({
            "type": "Terms/modules in CODEBASE.md not in Week 1 doc",
            "detail": ", ".join(sample) + (" ..." if len(only_codebase_phrases) > 5 else ""),
            "explanation": "Automated module graph and lineage include all parsed files; manual notes may focus on a subset.",
        })

    if not discrepancies:
        discrepancies.append({
            "type": "No structural discrepancies",
            "detail": "Section overlap and key phrases are similar.",
            "explanation": "Consider comparing prose or line-level details manually.",
        })

    lines = [
        "# Self-Audit Report",
        "",
        f"**Week 1 repo:** {repo_path}",
        f"**Week 1 doc:** {week1_doc.name}",
        f"**CODEBASE.md:** {codebase_md}",
        "",
        "## Discrepancies",
        "",
    ]
    for i, d in enumerate(discrepancies, 1):
        lines.append(f"### {i}. {d['type']}")
        lines.append("")
        lines.append(f"- **Detail:** {d['detail']}")
        lines.append(f"- **Explanation:** {d['explanation']}")
        lines.append("")

    report_path = out / "self_audit_report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote %s", report_path)
    return report_path
